[build]
  command = "npm install && npm run build"
  functions = "functions"
  publish = "public"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200

[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"